### ISSUE TITLE
cross-period analysis for quantifiers 

### ISSUE THREAD

**Issue by divine-comedian** [CommonsBuild/rad#29]
I noticed there is a section in the latest cross-period report of quantifier agreements - looks to be in progress.

I would like to request two graphs or something similar that would help us find "problem" quantifiers.
- score displacement - allowing us to see tendencies to underscore and overscore over many periods
- score correlation - allow us to see who scores the least like the others over many periods

and anything else perhaps you can think of that can let us zero in on quantifiers who might be causing our praise accuracy to become skewed.

![image](https://user-images.githubusercontent.com/67759413/173189008-a817b906-8177-42ea-9650-7c471103b8ed.png)

**Comment by kristoferlund** [comment]
@tree-pi could you have a look at this?

**Comment by tree-pi** [comment]
updated the cross-period analysis with these metrics!
